version: 1.0.{build}
image: Visual Studio 2019

environment:
  nodejs_version: '14'

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run build

test_script:
  - npm test

artifacts:
  - path: dist
    name: Webpack Build

deploy:
  provider: GitHub
  artifact: dist
  publish: true
